### ISSUE TITLE
Googleアナリティクスを導入する

### ISSUE THREAD

**Issue by iwaseasahi** [yokozawa0701/law_shikaku_navi#148]
## 目的・課題・背景・KPI
* Googleアナリティクスを導入します。

## 内容詳細
* [gem google-analytics-rails](https://github.com/bgarret/google-analytics-rails) を使用します。

**Comment by yokozawa0701** [comment]
@iwaseasahi 
`Google Tag Manager` を入れているので、
こちら不要です！
