### ISSUE TITLE
サービスのテーブルの追加

### ISSUE THREAD

**Issue by yokozawa0701** [yokozawa0701/law_shikaku_navi#44]
## 目的・課題・背景・KPI
#3 を参考。
corporates > schoolという関係になっているが、サービス一覧をまとめたい。
### 理由
* サイトビジットが資格スクエアを運営しているように、同じ会社が色々な予備校（サービス）を提供する可能性がある。

### 現状
* サイトビジット > 資格スクエア
* サイトビジット > 資格スクエア・リアル（東京）
* 伊藤塾 > 伊藤塾（東京校）
### 理想
* サイトビジット > 資格スクエア > 資格スクエア
* サイトビジット > 資格スクエア > 資格スクエア・リアル（東京）
* 伊藤塾 > 伊藤塾 > 伊藤塾（東京校）

## 内容詳細
* corporatesとshcoolsの間にservices（仮）のようなテーブルを追加してほしい

**Comment by iwaseasahi** [comment]
## テーブル設計
### テーブル定義書
* [テーブル定義書](https://docs.google.com/spreadsheets/d/1RmOyjzrjg_ZpSqufqqxiPLX-MMH5q0QCiKvkOFb-hDw/edit#gid=730772104)

### ER図

![スクリーンショット 2018-02-03 13.08.51.png](https://qiita-image-store.s3.amazonaws.com/0/142810/90daa61d-1cc9-9bea-ada9-6ac74bbab151.png "スクリーンショット 2018-02-03 13.08.51.png")

**Comment by iwaseasahi** [comment]
`leaning_servicesテーブル` を新規作成します。
