### ISSUE TITLE
テーブル設計 - SEO記事

### ISSUE THREAD

**Issue by iwaseasahi** [yokozawa0701/law_shikaku_navi#58]
## 目的・課題・背景・KPI
* SEO記事を作成できるテーブル設計を行う。

### 資料
* [テーブル定義書](https://docs.google.com/spreadsheets/d/1RmOyjzrjg_ZpSqufqqxiPLX-MMH5q0QCiKvkOFb-hDw/edit#gid=730772104)

#### SEO記事
* title
* description
* content
* サムネイル画像
* タグ
  * [gem acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on)を導入

**Comment by yokozawa0701** [comment]
descriptionの他にcontentsも欲しいですー
```
<meta name=”description”>
```
こっちにdescriptionを、記事の中身をcontentsにしたいです。

**Comment by iwaseasahi** [comment]
一番重要なものを記載し忘れてましたね。
